TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices.
> Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.
within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.
TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices. Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

In [27]:
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')
print("Tensorflow version:{}".format(tf.__version__))
print("Eager execution: {}".format(tf.executing_eagerly()))


Tensorflow version:2.13.0
Eager execution: True


## Tensor constant

In [28]:
vaish = tf.constant(42)
vaish

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [29]:
vaish.numpy()

42

In [30]:
##Specify the datatype
pw = tf.constant(1,dtype = tf.int64)
pw.numpy()

1

In [31]:
#Matrix form
X = tf.constant([[4,2],[9,5]])
print(X)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [32]:
X.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [33]:
#Print datatype and shape
print("shape:",X.shape)
print(X.dtype)

shape: (2, 2)
<dtype: 'int32'>


In [34]:
#two rows and 3 cols
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [35]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [36]:
#Adding constants
const1 = tf.constant([[3,4,5],[3,4,5]])
const2 = tf.constant([[1,2,3],[1,2,3]])
result = tf.add(const1 , const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


## Random constant

In [37]:
tf.random.normal(shape=(2,2),mean = 0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.10105084, -0.3523583 ],
       [-0.52853996, -0.3820071 ]], dtype=float32)>

In [38]:
tf.random.uniform(shape=(2,2),minval = 0,maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 8],
       [3, 2]], dtype=int32)>

## Variable

In [39]:
var0 = 24 #python variable
var1 = tf.Variable(42)
var2= tf.Variable([[[0.,1.,2,],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [40]:
#The dataype can be explicitly specified
float_var64 = tf.Variable(89,dtype = tf.float64)
float_var64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>

In [41]:
# to reassign a variable
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [42]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [43]:
initial_value = tf.random.normal(shape = (2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.5446535 , 0.66284484],
       [0.8076884 , 0.72260696]], dtype=float32)>


In [44]:
new_value = tf.random.normal(shape = (2,2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]
        

In [45]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

In [46]:
tensor= tf.Variable([[[0.,1.,2,],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
print(tensor.shape)

(2, 2, 3)


In [49]:
tensor1 = tf.reshape(tensor,[2,6])# 2rows 6 cols
tensor2 = tf.reshape(tensor,[1,12])#1 rows and 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [50]:
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

## RANK(dimensions) of a tensor

In [52]:
tf.rank(tensor).numpy()

3

## Specifying an element

In [53]:
tensor3 = tensor[1,0,2] #slice 1 , row 0 , columns 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

## Casting a tensor to numpy/python variable

In [54]:
print(tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [55]:
print(tensor[1,0,2].numpy())

8.0


## Size

In [57]:
tensor_size = tf.size(input = tensor).numpy()
tensor_size

12

## Mathementical opearations

In [59]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.06376745 -0.01287734]
 [ 0.01615601  0.09939475]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.3841348  -0.9461991 ]
 [-3.3021653  -0.03553364]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.3203673  -0.95907646]
 [-3.2860093   0.06386111]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.7433699e+00 9.1982764e-01]
 [1.0797857e+01 4.0782411e-03]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.26703718 0.38324666]
 [0.03740282 1.0659443 ]], shape=(2, 2), dtype=float32)


In [60]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

## Broadcasting

In [61]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


## Transpose matric multiplication

In [62]:
matrix1 = tf.constant([[3,4,3]])
matrix2 = tf.constant([[1,2,1]])
tf.matmul(matrix1,tf.transpose(matrix2))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

## Casting

In [64]:
print(tensor)
i = tf.cast(tensor1,dtype = tf.int32)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


## With truncation

In [67]:
j = tf.cast(tf.constant(4.9),dtype = tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Declaring ragged tensor

In [71]:
ragged = tf.ragged.constant([[5,2,6,1],[],[4,10,7],[8],[6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])


<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


## Find the squaed difference between two tensors

In [73]:
varx = [1,3,5,7,11]
vary = 5 # 1-5 = 4 and square of 4 = 16 
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

## Mean

In [74]:
numbers = tf.constant([[4.,5.],[7.,3.]])


In [75]:
tf.reduce_mean(input_tensor = numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [77]:
# find mean across columns
tf.reduce_mean(input_tensor = numbers,axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

## Setting the seed

In [82]:
tf.random.set_seed(11)# everytime it will generate same value
ran1 = tf.random.uniform(shape = (2,2),maxval = 10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval = 10, dtype = tf.int32)
print(ran1)
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [85]:
dice1 = tf.Variable(tf.random.uniform([10,1],minval = 1, maxval = 7 , dtype = tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1],minval = 1, maxval = 7 , dtype = tf.int32))
dice_sum = dice1 + dice2

resulting_matrix = tf.concat(values = [dice1 , dice2 , dice_sum],axis = 1)
print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 2  2  4]
 [ 4  2  6]
 [ 1  4  5]
 [ 3  1  4]
 [ 5  5 10]
 [ 6  1  7]
 [ 1  3  4]
 [ 2  5  7]
 [ 3  6  9]], shape=(10, 3), dtype=int32)


In [89]:
## Argument(index)
t5 = tf.constant([2,11,5,42,7,19,-6,-11,29])
print(t5)

i = tf.argmax(input = t5)
print("index of max",i)
print("max element",t5[i].numpy())

i = tf.argmin(input = t5,axis = 0).numpy()
print("index of min",i)
print("min element",t5[i].numpy())

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max tf.Tensor(3, shape=(), dtype=int64)
max element 42
index of min 7
min element -11


## Saving and restoring tensor values using a checkpoint

In [91]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint = tf.train.Checkpoint(var = variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable)
checkpoint.restore(save_path)
print(variable)
                            

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


## tf.function

In [92]:
def f1(x,y):
    return tf.reduce_mean(input_tensor=tf.multiply(x**2,5)+y**2)
f2 = tf.function(f1)
x = tf.constant([4.,-5.])
y = tf.constant([2.,3.])
assert f1(x,y).numpy() == f2(x,y).numpy()

In [93]:
(5*pow(4,2)+pow(2,2)+5*pow(-5,2)+pow(3,2))/2

109.0

## Calculate gradient

In [94]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.1684204 -0.5020665]
 [ 0.9471321  0.5898169]], shape=(2, 2), dtype=float32)


In [96]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.1684204 -0.5020665]
 [ 0.9471321  0.5898169]], shape=(2, 2), dtype=float32)


In [97]:
#double derivative
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
       c = tf.sqrt(tf.square(a)+tf.square(b))
       dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    
    print(d2c_d2a)

tf.Tensor(
[[0.57568985 0.7655419 ]
 [0.12753117 0.9209411 ]], shape=(2, 2), dtype=float32)
